# Here you can create your server's group.
# Be sure to use the name of the server describe in your BungeeCord configuration
# Structure:
# group:
#   - {group name}:
#     - {server name 1}
#     - {server name 2}
group:
  - survival:
      - survival1
      - survival2
  - creative:
      - creative1
  - skyblock:
      - skyblock1